## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [2]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [65]:
# in one line of code
titanic_df.groupby('Pclass').agg(Avg_age = ('Age','mean'), Missing_val = ('Age',lambda x: x.isnull().sum()))

          Avg_age  Missing_val
Pclass
1       38.233441           30
2       29.877630           11
3       25.140620          136

In [25]:
# code here
titanic_df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [66]:
def ifnan(group):
  return group['Age'].isnull().sum()

titanic_df.groupby('Pclass').apply(ifnan, include_groups = False)

Pclass
1     30
2     11
3    136
dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [121]:
# code here
def fill_embarked(group):
  group['Embarked'] = group['Embarked'].fillna(group['Embarked'].mode()[0])
  return group

new_df = titanic_df.groupby('Pclass').apply(fill_embarked,include_groups=False)
new_df.groupby('Pclass')['Embarked'].value_counts(ascending=True)

Pclass  Embarked
1       Q             2
        C            85
        S           129
2       Q             3
        C            17
        S           164
3       C            66
        Q            72
        S           353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [122]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [129]:
# code here
titanic_df.groupby(['Embarked','Pclass'])['Fare'].agg(lambda x: round(x.mean(),2))
titanic_df.groupby(['Embarked','Pclass'])['Fare'].mean().round(2)

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.36
          2          20.33
          3          14.64
Name: Fare, dtype: float64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [130]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [144]:
# code here
def z_normalization(group,cols_to_perform):
  for col in cols_to_perform:
    group[col] = (group[col] - group[col].mean()) / group[col].std()
  return group

z_normdf = fifa_df.groupby('Team').apply(z_normalization,['Passes','Passes Completed','Attempted Line Breaks','Completed Line Breaks'],include_groups=False)

In [141]:
z_normdf.groupby('Team').agg({
    'Passes': ['min','max'],
    'Yellow Cards':['min','max','mean'],
    'Attempted Line Breaks': ['max','min','std'],
    'Possession (%)': 'mean'
})

                  Passes           Yellow Cards                \
                     min       max          min max      mean
Team
Argentina      -1.510257  1.685214            0   8  2.285714
Australia      -1.114789  0.932782            0   3  1.750000
Belgium        -1.082696  0.888950            1   3  1.666667
Brazil         -0.928871  1.609122            0   3  1.200000
Cameroon       -0.875605  1.089713            1   5  2.666667
Canada         -1.120897  0.800641            2   4  2.666667
Costa Rica     -1.013178  0.986279            1   3  2.000000
Croatia        -1.441280  1.093005            0   2  1.142857
Denmark        -1.046208  0.946290            1   2  1.666667
Ecuador        -0.883020  1.085876            0   2  1.000000
England        -0.877731  1.705844            0   1  0.200000
France         -1.219077  1.571019            0   3  1.142857
Germany        -1.131449  0.765392            0   3  1.000000
Ghana          -1.045786  0.946861            2   4  2.666667
Iran           -0.820695  1.113800            2   3  2.333333
Japan          -1.001479  0.979825            0   3  1.500000
Korea Republic -1.157924  0.877868            1   2  1.500000
Mexico         -0.918398  1.065342            1   4  2.333333
Morocco        -1.384362  1.662218            0   3  1.285714
Netherlands    -1.051749  1.428668            0   4  1.800000
Poland         -0.694755  1.483035            1   3  1.750000
Portugal       -1.646177  1.035658            0   3  1.200000
Qatar          -1.147558  0.684833            0   4  2.333333
Saudi Arabia   -0.667896  1.149691            2   6  4.666667
Senegal        -1.214144  1.235077            1   3  1.750000
Serbia         -1.089807  0.875419            2   7  4.000000
Spain          -1.498758  0.554601            0   1  0.500000
Switzerland    -1.469082  0.754945            1   4  2.250000
Tunisia        -0.965692  1.031097            1   3  1.666667
United States  -1.136338  0.860862            0   4  1.250000
Uruguay        -0.931702  1.056570            1   3  2.000000
Wales          -0.971590  1.026174            1   2  1.666667

               Attempted Line Breaks                Possession (%)
                                 max       min  std           mean
Team
Argentina                   1.757406 -1.027917  1.0      49.285714
Australia                   0.961409 -1.187623  1.0      31.250000
Belgium                     1.109400 -0.832050  1.0      49.000000
Brazil                      1.085013 -1.627519  1.0      50.400000
Cameroon                    0.788942 -1.124661  1.0      38.333333
Canada                      0.865260 -1.094819  1.0      44.333333
Costa Rica                  0.590132 -1.154606  1.0      27.333333
Croatia                     1.187420 -1.785063  1.0      47.428571
Denmark                     1.000000 -1.000000  1.0      51.333333
Ecuador                     1.019020 -0.979827  1.0      42.666667
England                     1.354603 -1.172641  1.0      57.200000
France                      1.147789 -1.327966  1.0      44.857143
Germany                     1.036065 -0.959538  1.0      53.000000
Ghana                       0.979199 -1.019578  1.0      37.000000
Iran                        0.640642 -1.152297  1.0      31.666667
Japan                       1.377855 -0.948495  1.0      30.250000
Korea Republic              0.840338 -1.449814  1.0      42.250000
Mexico                      0.589590 -1.154613  1.0      46.666667
Morocco                     1.006855 -1.718366  1.0      34.285714
Netherlands                 1.128588 -1.222637  1.0      44.000000
Poland                      0.626272 -1.493418  1.0      32.000000
Portugal                    1.655185 -0.796941  1.0      53.800000
Qatar                       1.115767 -0.815368  1.0      39.333333
Saudi Arabia                0.976238 -1.022179  1.0      36.666667
Senegal                     1.343085 -1.077420  1.0      38.500000
Serbia                      1.066614 -0.916387  1.0      42.666667
Spain                       1.193911 -0.905726  1.0      67.000000
Switzerland                 1.024097 -1.300880  1.0      43.000000
Tunisia                     0.805353 -1.119304  1.0      38.666667
United States               0.767335 -1.435367  1.0      47.000000
Uruguay                     1.149932 -0.665750  1.0      41.000000
Wales                       0.867461 -1.093756  1.0      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [149]:
# code here
ipl_df = pd.read_csv('/content/ipl_deliveries.csv')
ipl_df.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [188]:
new_ipl_df = ipl_df[ipl_df['innings'] == 2]

Batter_HScore = new_ipl_df.groupby(['ID','batter'])['batsman_run'].sum().nlargest(1).index[0][1]

df = new_ipl_df.groupby(['batter']).agg({
    'batsman_run': 'sum',
    'ballnumber': 'count'
})
df = df[df['ballnumber'] > 100]
df['Strike_rate'] = ( df['batsman_run'] / df['ballnumber'] ) * 100

batter_hStikeRate = df.nlargest(columns=['Strike_rate'], n=1).index[0]

print(Batter_HScore)
print(batter_hStikeRate)

PC Valthaty
PJ Cummins

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [234]:
# code here
new_df = ipl_df.groupby(['bowler','batter']).agg(
    Runs = ('total_run','sum'),
    Out_Count = ('isWicketDelivery','sum')
    ).reset_index().nlargest(1,'Out_Count',keep='all')
if len(new_df) > 1:
  new_df = new_df.nsmallest(1,'Runs')
new_df

          bowler     batter  Runs  Out_Count
20710  SP Narine  RG Sharma   140          8

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [191]:
# code here
ipl_df.groupby(['batter','non-striker'])['total_run'].sum().idxmax()

('AB de Villiers', 'V Kohli')

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [223]:
# code here
new_df = ipl_df.groupby(['batter','non-striker']).agg(
    Runs = ('batsman_run','sum'),
    Avg=('batsman_run','mean'),
    Balls = ('ballnumber','count')
    )

new_df.reset_index(inplace=True)
new_df['StrikeRate'] = (new_df['Runs'] / new_df['Balls']) * 100
new_df.rename(columns={
    'batter': 'Batsman1',
    'non-striker':'Batsman2',
},inplace=True)

new_df.drop(columns='Balls',inplace=True)
new_df

            Batsman1         Batsman2  Runs       Avg  StrikeRate
0     A Ashish Reddy         A Mishra    19  1.266667  126.666667
1     A Ashish Reddy  AA Jhunjhunwala     3  1.000000  100.000000
2     A Ashish Reddy         CL White     3  1.000000  100.000000
3     A Ashish Reddy     DB Ravi Teja     6  2.000000  200.000000
4     A Ashish Reddy        DJG Sammy    26  1.444444  144.444444
...              ...              ...   ...       ...         ...
8057          Z Khan        S Aravind     0  0.000000    0.000000
8058          Z Khan         S Nadeem     3  0.600000   60.000000
8059          Z Khan       SL Malinga    17  2.125000  212.500000
8060          Z Khan     SR Tendulkar     2  0.666667   66.666667
8061          Z Khan        SS Tiwary    21  0.840000   84.000000

[8062 rows x 5 columns]